[package]
name = "rapidmq"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.3", features = ["openssl"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.3", features = ["v4"] }
rocksdb = "0.20"
tokio = { version = "1.0", features = ["full"] }
raft = "0.7"
bincode = "1.3"
tonic = { version = "0.8", features = ["tls"] }
prost = "0.11"
openssl = "0.10"
bcrypt = "0.13"
prometheus = "0.13"
lazy_static = "1.4"

[build-dependencies]
tonic-build = "0.8"